spring:
  profiles:
    active: dev
  application:
    name: ${projectName}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#服务端口、线程数
server:
  port: xxxx
  tomcat:
    threads:
      min-spare: 100
      max: 500

#FeignClient超时配置(ms)
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 1000