server:
  port: 9002


spring:
  freemarker:
    #       设定ftl文件路径
    tempalte-loader-path: classpath*:/templates
    #        关闭缓存，及时刷新，上线生产环境需要修改为true
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl


smalld:
  code:
    input: /data/codes/smalld-demo
    output: /data/codes/output
