#服务配置
server:
  port: 9001

#spring相关配置
spring:
  application:
    name: smalld-gateway
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      cache:
        enabled: true
        caffeine:
          spec: initialCapacity=500,expireAfterWrite=5s